### ISSUE TITLE
Mesh for an ellipsoid 

### ISSUE THREAD

**Issue by nilswagner** [nschloe/meshzoo#40]
Like meshzoo.icosa_sphere(10) a function meshzoo.ellipsoid(a=4.5,b=6.0,c=3.) would be appreciated.

https://en.wikipedia.org/wiki/Ellipsoid

**Comment by nschloe** [comment]
That should be as simple as scaling the x, y, z coordinates, right?

(Unrelated: If you find the time, feel free to reply here: https://github.com/nschloe/meshio/issues/696.)

**Comment by nschloe** [comment]
Closing for lack of response. Feel free to reopen at any time though!
