### ISSUE TITLE
meshzoo.cube cells have 4 vertices

### ISSUE THREAD

**Issue by twhughes** [nschloe/meshzoo#49]
When generating a cube as in the readme:

```python
points, cells = meshzoo.cube(
    xmin=0.0, xmax=1.0,
    ymin=0.0, ymax=1.0,
    zmin=0.0, zmax=1.0,
    nx=11, ny=11, nz=11
)
```
I noticed that the `cells` array contains 4 points.
```python
>>> cells.shape
(5000, 4)
```

In the picture from the readme it seems to be made up of triangles.

Is there a version of `meshzoo.cube` that meshes the cube in terms of triangles?

Sorry if I am misunderstanding,
thanks

**Comment by nschloe** [comment]
They are tetrahedra.
