### ISSUE TITLE
Cell order not consistent with normals

### ISSUE THREAD

**Issue by maxschommer** [nschloe/meshzoo#53]
For a given cell (p1, p2, p3) with a normal n, then typical convention is that:

`dot(cross(p2-p1, p3 - p2), n) > 0`

The cell ordering is inconsistent for many of the functions such as tetra_sphere, octa_sphere,  uv_sphere (from what I've tested) and possibly more. 

Since all of the sphere normals are equal to the positions, then a simple fix would be:

```
fixed_cells = []
for cell in cells:
            p1 = points[cell[0], :]
            p2 = points[cell[1], :]
            p3 = points[cell[2], :]
            n = normals[cell[0], :]
            if np.dot(np.cross(p2 - p1, p3 - p2), n) < 0:
                fixed_cells.append([cell[2], cell[1], cell[0]])
            else:
                fixed_cells.append(cell[0], cell[1], cell[2])
```

**Comment by nschloe** [comment]
Good call. The suggested fix is computationally a bit expensive, but I'll look into getting the ordering right.
