### ISSUE TITLE
Icosasphere refinement

### ISSUE THREAD

**Issue by alexj94** [nschloe/meshzoo#55]
Hi,
I recently installed your library and used the computed geometries with some differentiable renderers in a 3D object generation pipeline. In particular, I'm interested in the icosasphere as a symmetrical shape. The problem is that the rendered shape is actually an icosahedron with no refinement to obtain an icosasphere. Do you plan to add this refinement operation or have any idea on how to do it correctly?

**Comment by nschloe** [comment]
The only argument to the method is a refinement parameter.

**Comment by alexj94** [comment]
I know but the resulting geometry is not spherical after the rendering. I'm using two different renderers and each one obtains the same geometry that is more similar to an icosahedron than an icosasphere as in the README file. I give you two rendered examples (the first using Neural Mesh Renderer and the second using DIB-Renderer) using an icosasphere with n=8 just to know if the output is actually correct or not.
![shape](https://user-images.githubusercontent.com/48673675/98523590-602d5100-2276-11eb-9a42-c97c70f06dd9.png)
![example](https://user-images.githubusercontent.com/48673675/98523594-60c5e780-2276-11eb-8d48-ceaec1ae4adc.gif)

**Comment by nschloe** [comment]
Good catch! I'll fix that right away and add tests.

**Comment by nschloe** [comment]
Fixed now. Thanks again for the report.

**Comment by alexj94** [comment]
Yes thanks for the quick correction. I confirm that now it works fine with both renderers.
![shape](https://user-images.githubusercontent.com/48673675/98526859-940a7580-227a-11eb-82db-b59a3778623b.png)
![example](https://user-images.githubusercontent.com/48673675/98526862-94a30c00-227a-11eb-84d3-22f74d595f66.gif)
