### ISSUE TITLE
Insert mid-nodes for quadratic elements?

### ISSUE THREAD

**Issue by adtzlr** [nschloe/meshzoo#64]
Hi Nico,

nice zoo :wolf: :frog: :tiger: :koala: :bear:.

Does meshzoo support the generation of ~~higher-order~~ *quadratic (edge-based)* meshes? With "quadratic" I mean e.g. the ~~(bi-)~~ quadratic quads, triangles, hexahedrons or tetrahedrons from VTK. Or do you know any open source python package that can handle this task? Ideally not only the creation of mid-side nodes but also some kind of removing duplicated nodes. I just wanted to ask before doing it myself.

Thanks!

Best regards,
Andreas

**Comment by nschloe** [comment]
Interesting question. Right now, meshzoo can't create higher-order cells yet, but that would definitely be something to think about. If you need this right now, you best implement it yourself, perhaps even in meshzoo.

**Comment by adtzlr** [comment]
> Interesting question. Right now, meshzoo can't create higher-order cells yet, but that would definitely be something to think about. If you need this right now, you best implement it yourself, perhaps even in meshzoo.

Okay thanks!

**Comment by adtzlr** [comment]
As a starting point I took my `merge` function which I wrote some time ago. It is not the fastest piece of code, but quite easy to understand:

```python
def merge(points, cells):
    "Merge duplicate points and update cells accordingly."

    # unique array of points with additional output
    points_unique, index, inverse = np.unique(
        points, return_index=True, return_inverse=True, axis=0
    )

    # original indices
    original = np.arange(len(points))

    # mask where inverse-indices of unique array not equal original indices
    mask = (inverse != original)
    
    # find and replace variables
    find = original[mask]
    replace = inverse[mask]

    # init unique cells array
    cells_unique = cells.copy()

    # loop over find-replace mappings (probably slow...)
    for i, j in zip(find, replace):
        cells_unique[cells == i] = j

    return points_unique, cells_unique
```

**Comment by adtzlr** [comment]
Let's start with a simple example of two triangle cells.

```python
import numpy as np

points = np.array([[ 0., 0.],
                   [ 1., 0.],
                   [ 0., 1.],
                   [ 1., 1.],
                   ])

cells = np.array([[ 0, 1, 2],
                  [ 3, 2, 1]])
```

Next, I'll define some helpers:
* number of points `npts`,
* dimension of the point-coordinates `dim` and 
* number of cells `ncls`

and an extended cells-array - I called it `edges` but this was probably not the wisest choice.

```python
edges = np.hstack((cells, cells[:,0].reshape(-1,1)))
```

Then we obtain mid-points on edges with:

```python
points_edges = np.mean([
    points[edges][:, 1:  ], 
    points[edges][:,  :-1]
], axis=0)
```

and mid-points on faces by simply evaluating

```python
points_faces = np.mean(points[cells], axis=1)
```

We create two additionals `cells`-arrays - one for the connectivity of edges - mid-points and another one for faces - mid-points. Of course we do have to take care of the offsets.

```python
npts_edges = points_edges.reshape(-1, dim).shape[0]
npts_faces = points_faces.reshape(-1, dim).shape[0]

cells_edges = npts + np.arange(npts_edges).reshape(ncls, -1)
cells_faces = npts + npts_edges + np.arange(npts_faces).reshape(ncls, -1)
```

Now we are able to stack our new `points` and `cells` arrays. In order to merge duplicated points and update the cells, we call the above posted `merge(points, cells)` function.

```python
points_unique, cells_unique = merge(points_new, cells_new)
```

**Comment by adtzlr** [comment]
**TO-DO**: For three dimensional `tetrahedrons` and `hexahedrons` a loop over all faces, which have to be sliced out from the cell-connectivity should complete this conversion. To complete the conversion, the interior volume-points as the coordinate-mean per cell-coordinates would have to be added.

That would be more or less how I would do that - what do you think about that?

**Comment by adtzlr** [comment]
Things which would have to be concerned:

- Which cell-point connectivity should be used (e.g. VTK convention)?
- How to implement this in `meshzoo`? Is this even a good idea or keep `meshzoo` as simple as possible?

**Comment by nschloe** [comment]
I think in principle it should go like this:

  * collect all edges
  * identify unique edges by `np.unique` (or [`npx.unique_rows`](https://github.com/nschloe/npx#unique_rows))
  * add point for each edge
  * add point ids to the cell array using np.unique info

The VTK convention should be used indeed.

**Comment by adtzlr** [comment]
> I think in principle it should go like this:
> 
> * collect all edges
> * identify unique edges by `np.unique` (or [`npx.unique_rows`](https://github.com/nschloe/npx#unique_rows))
> * add point for each edge
> * add point ids to the cell array using np.unique info
> 
> The VTK convention should be used indeed.

Yes, that would avoid the creation of all the duplicated points. I'll see what I can do in the next days. Thanks!

**Comment by adtzlr** [comment]
I created a code snippet which works on both triangles and quads:

```python
import numpy as np

points = np.array([[0,0],
                   [1,0],
                   [2,0],
                   [0,1],
                   [1,1],
                   [2,1]], dtype=float)


cells = np.array([[0,1,4,3],
                  [1,2,5,4]])

npoints = len(points)
ncells = len(cells)

idx = [*range(1, cells.shape[1]), 0]

edges = np.dstack((cells, cells[ :, idx])).reshape(-1, 2)
edges_sorted = np.sort(edges, axis=1)
edges_unique, index, inverse, counts = np.unique(
    edges_sorted, True, True, True, axis=0
)

points_edges = np.mean(points[edges_unique.T], axis=0)

cells_edges = (npoints + inverse).reshape(ncells,-1)

# this will get more complicated for `quadratic-tetra` and `quadratic-hexahedron`
faces = cells

faces_sorted = np.sort(faces, axis=1)
faces_unique, index, inverse, counts = np.unique(
    faces_sorted, True, True, True, axis=0
)

npoints_edges = len(points_edges)

points_faces = np.mean(points[faces_unique.T], axis=0)

cells_faces = (npoints + npoints_edges + inverse).reshape(ncells,-1)

points_new = np.vstack((points, points_edges, points_faces))
cells_new = np.hstack((cells, cells_edges, cells_faces))

# add points_volume for `tetra` and `hexahedron`
```

To-Do:
* collect faces for tetrahedrons and hexahedrons similar to edges in 2d
* collect volumes (easy) for tetrahedrons and hexahedrons 

The code parts for edge and face detection are very similar; they could be generalized in a function `collect()`...

**Comment by adtzlr** [comment]
Got it! I have a solution prepared for triangles and tetrahedrons. Should be easy to implement in meshzoo. I'll try to create a pull request (will take me some days). I'll post the script in the meanwhile. I had to fix tetrahedron volumes though before converting. Attached is the script with two VTK outputs using `meshio`: the first one is the original mesh and the second one containing quadratic cells. :rocket:

```python
# -*- coding: utf-8 -*-
"""
Created on Thu Jul  8 18:41:14 2021

@author: Andreas
"""

import numpy as np
import meshzoo
import meshio

points, cells = meshzoo.rectangle_tri(a0=(0, 0), a1=(1, 1), n=16)
cell_type = "triangle"


points, cells = meshzoo.cube_tetra(a0=(0, 0, 0), a1=(1, 1, 1), n=16)
cell_type = "tetra"


def fix(points, cells, cell_type):
    "Fixes cells array of tetrahedrals to ensure cell volume > 0."

    if cell_type == "tetra":

        # extract point 0 of all cells and reshape and repeat
        p0 = points[cells][:, 0].reshape(len(cells), 1, 3)

        # calculate vertice "i" as v[:, i]
        v = points[cells] - np.repeat(p0, 4, axis=1)

        # calculate volume by the triple product
        volume = np.einsum("...i,...i->...", v[:, 3], np.cross(v[:, 1], v[:, 2]))

        # permute point entries for cells with volume < 0
        cells[volume < 0] = cells[volume < 0][:, [0, 2, 1, 3]]

    return points, cells


def collect_edges(points, cells, cell_type):
    """ "Collect all unique edges (of triangles or tetrahedrons),
    calculate and return midpoints on edges as well as the additional
    cells array."""

    supported_cell_types = ["triangle", "tetra"]

    if cell_type not in supported_cell_types:
        raise TypeError("Cell type not implemented.")

    number_of_edges = {"triangle": 3, "tetra": 6}

    # k-th edge is (i[k], j[k])
    i = [0, 1, 2, 3, 3, 3][: number_of_edges[cell_type]]
    j = [1, 2, 0, 0, 1, 2][: number_of_edges[cell_type]]

    edges_to_stack = cells[:, i], cells[:, j]

    # sort points of edges
    edges = np.sort(np.dstack(edges_to_stack).reshape(-1, 2), axis=1)

    # obtain unique edges and inverse mapping
    edges_unique, inverse = np.unique(edges, False, True, False, 0)

    # calculate midpoints on edges as mean
    points_edges = np.mean(points[edges_unique.T], axis=0)

    # create the additionals cells array
    cells_edges = inverse.reshape(len(cells), -1)

    return points_edges, cells_edges


def add_points_edges(points, cells, cell_type):
    """ "Add midpoints on edges for given points and cells
    and update cell_type accordingly."""

    cell_types_new = {"triangle": "triangle6", "tetra": "tetra10"}

    # collect edges
    points_edges, cells_edges = collect_edges(
        points,
        cells,
        cell_type,
    )

    # add offset to point index for edge-midpoints
    # in additional cells array
    cells_edges += len(points)

    # vertical stack of points and horizontal stack of edges
    points_new = np.vstack((points, points_edges))
    cells_new = np.hstack((cells, cells_edges))

    return points_new, cells_new, cell_types_new[cell_type]


points, cells = fix(points, cells, cell_type)
points2, cells2, cell_type2 = add_points_edges(points, cells, cell_type)

mesh = meshio.Mesh(points, [(cell_type, cells)])
mesh.write("mesh.vtk")

mesh = meshio.Mesh(points2, [(cell_type2, cells2)])
mesh.write("mesh2.vtk")
```

**Comment by nschloe** [comment]
Sweet! Looking forward to a PR, a nice addition to meshzoo!

**Comment by adtzlr** [comment]
I think my question in the beginning was a bit misleading. I titled the issue **Insert mid-nodes for quadratic elements?** wheras in the description i wrote about higher-order cells. As higher-order Lagrange and quadratic cells are treated in a different way in VTK, I would suggest to be happy with quadratic cell types for now.

I'll implement `quad -> quad8` and `hexahedron -> hexahedron20` as this is a straightforward addition but I'll not add `hexahedron -> hexahedron27` for now. That would involve face and volume midpoints too.
