### ISSUE TITLE
Some cells of tet meshes have negative volumes

### ISSUE THREAD

**Issue by adtzlr** [nschloe/meshzoo#68]
If the cell volumes of a tet mesh are calculated by the triple product of edge vectors (see https://en.wikipedia.org/wiki/Tetrahedron#Volume) it seems that the cell connectivity of `meshzoo` leads to some negative cell volumes. Should this be fixed? Let's have a look at the following code snippet. First, I'll define a (nice and fast 😎) function for the volume calculation of tet cells.

```python
import numpy as np

def cell_volumes_tetra(points, cells):
    "Calculate cell volumes of tetrahedrons."

    # extract point no. 0 of all cells and reshape
    p0 = points[cells][:, 0].reshape(len(cells), 1, 3)
    
    # calculate edge vectors "i" as v[:, i] for all cells
    edges = (points[cells] - np.repeat(p0, 4, axis=1))[:, 1:]
    
    # evaluate cell volumes by the triple product
    # cyclic permutations lead to identical results (0,1,2), (1,2,0), (2,0,1)
    cell_volumes = np.einsum("...i,...i->...", edges[:, 0], 
                             np.cross(edges[:, 1], edges[:, 2])) / 6

    return cell_volumes
```

Next, let's define a tet mesh.

```python
import meshzoo

points, cells = meshzoo.cube_tetra(a0=(0,0,0), a1=(1,1,1), n=2)
```

and evaluate volumes...

```python
volumes = cell_volumes_tetra(points, cells)

volumes
# >>> array([-0.16666667, -0.16666667, -0.33333333, -0.16666667, -0.16666667])

volumes.sum()
# >>> -0.9999999999999999
```

A simple fix would be to swap two colums of the cells array for cells with negative volumes.

```python
# easy fix of negative volumes
# permute point entries for cells with volume < 0
cells[volumes < 0] = cells[volumes < 0][:, [0, 2, 1, 3]]

# check again
volumes = cell_volumes_tetra(points, cells)
# >>>array([0.16666667, 0.16666667, 0.33333333, 0.16666667, 0.16666667])

volumes
# >>> array([0.16666667, 0.16666667, 0.33333333, 0.16666667, 0.16666667])

volumes.sum()
# >>> .9999999999999999
```

What do you think @nschloe?

**Comment by adtzlr** [comment]
P.S.: In the above example all cell volumes are negative - but for tet meshes with `n>2` some cell volumes are positive and some are negative.

**Comment by adtzlr** [comment]
Oh, is this related to issue #53 ? I'll have a look...

**Comment by nschloe** [comment]
> Should this be fixed?

Absolutely! Best with a test, you already have the code for that.

**Comment by nschloe** [comment]
When computing with meshplex, it all seems okay:
```
import meshplex
import meshzoo

points, cells = meshzoo.cube_tetra(a0=(0,0,0), a1=(1,1,1), n=2)

mesh = meshplex.Mesh(points, cells)

print(mesh.signed_cell_volumes)
```
```
[0.16666667 0.16666667 0.33333333 0.16666667 0.16666667]
```
Perhaps there's an issue with your volume computation?

**Comment by adtzlr** [comment]
> When computing with [meshplex](https://github.com/nschloe/meshplex/), it all seems okay:
> 
> ```python
> import meshplex
> import meshzoo
> 
> points, cells = meshzoo.cube_tetra(a0=(0,0,0), a1=(1,1,1), n=2)
> 
> mesh = meshplex.Mesh(points, cells)
> 
> print(mesh.signed_cell_volumes)
> ```
> 
> ```
> [0.16666667 0.16666667 0.33333333 0.16666667 0.16666667]
> ```
> 
> Perhaps there's an issue with your volume computation?

You really have a library for everything 👍🏻 I'll check again.

**Comment by adtzlr** [comment]
It seems `meshplex` is indexing the edges the other way round than my function.  Anyway, that doesn't make things better.

```python
import numpy as np
import meshzoo

points, cells = meshzoo.cube_tetra(a0=(0,0,0), a1=(1,1,1), n=5)

import meshplex
mesh = meshplex.Mesh(points, cells)
print(mesh.signed_cell_volumes)
```

```
[ 0.02083333 -0.02083333 -0.02083333  0.02083333 -0.02083333  0.02083333
  0.02083333 -0.02083333  0.02083333 -0.02083333 -0.02083333  0.02083333
 -0.02083333  0.02083333  0.02083333 -0.02083333  0.04166667 -0.04166667
 -0.04166667  0.04166667 -0.04166667  0.04166667  0.04166667 -0.04166667
  0.02083333 -0.02083333 -0.02083333  0.02083333 -0.02083333  0.02083333
  0.02083333 -0.02083333  0.02083333 -0.02083333 -0.02083333  0.02083333
 -0.02083333  0.02083333  0.02083333 -0.02083333]
```

whereas my function gives

```python
print(cell_volumes_tetra(points, cells))
```

```
[-0.02083333  0.02083333  0.02083333 -0.02083333  0.02083333 -0.02083333
 -0.02083333  0.02083333 -0.02083333  0.02083333  0.02083333 -0.02083333
  0.02083333 -0.02083333 -0.02083333  0.02083333 -0.04166667  0.04166667
  0.04166667 -0.04166667  0.04166667 -0.04166667 -0.04166667  0.04166667
 -0.02083333  0.02083333  0.02083333 -0.02083333  0.02083333 -0.02083333
 -0.02083333  0.02083333 -0.02083333  0.02083333  0.02083333 -0.02083333
  0.02083333 -0.02083333 -0.02083333  0.02083333]
```

**Comment by adtzlr** [comment]
Let's have a look at the elementary example.

```python
points = np.array([[0,0,0],
                   [1,0,0],
                   [0,1,0],
                   [0,0,1]])

cells = np.array([[0,1,2,3]])

print(cell_volumes_tetra(points, cells))
```

`[0.16666667]`

Whereas meshplex is calculating...

```python
print(meshplex.Mesh(points, cells).signed_cell_volumes)
```

`[-0.16666667]`

**Comment by nschloe** [comment]
Good example. I'll take a look later.

**Comment by adtzlr** [comment]
Thanks! FYI: I came across this issue while using my own word-in-progress FEA code ([adtzlr/felupe](https://github.com/adtzlr/felupe)) in combination with a tet mesh from meshzoo.

I assumed that the normal of the triangle `points[[0,1,2]]` points in the direction of `points[3]` as described here: https://vtk.org/doc/nightly/html/classvtkTetra.html (see section **Detailed Description**):  

*The tetrahedron is defined by the four points (0-3); where (0,1,2) is the base of the tetrahedron which, using the right hand rule, forms a triangle whose normal points in the direction of the fourth point.*

```python
# 1   0   0
# 0 x 1 = 0
# 0   0   1
```

**Comment by nschloe** [comment]
Btw, the signed volume of an n-simplex is defined only in nD, and there it is
```math
\det\begin{pmatrix}
v_0 & v_1 & \dots & v_n\\
1 & 1 & \dots & 1
\end{pmatrix}
```
(Rendered with [xdoc](https://github.com/nschloe/xdoc).) See https://en.wikipedia.org/wiki/Simplex#Volume.

So for tetrahedra, this is exactly opposite as VTK suggests.

**Comment by adtzlr** [comment]
Thanks @nschloe for pointing this out. Wikipedia is also unclear here because both formulas give opposite results. Let's take again the tetrahedron

```python
points = np.array([[0,0,0],
                   [1,0,0],
                   [0,1,0],
                   [0,0,1]])

cells = np.array([[0,1,2,3]])
```

then define the difference-vectors of the vertices `v1-v0`, `v2-v0` and `v3-v0`

```python
v10 = np.array([[1], 
                [0], 
                [0]])

v20 = np.array([[0], 
                [1], 
                [0]])

v30 = np.array([[0], 
                [0], 
                [1]])
```

and stack them all together (horizontally). In this simple example this leads to the identity matrix. The volume is positive.

```python
A = np.hstack((v10, v20, v30))
cell_volume = np.linalg.det(A) / 6
```

Taking the other formula you posted, the cell volume is negative.

```python
A = np.pad(points.T, ((0,1), (0,0)), constant_values=1)
cell_volume_2 = np.linalg.det(A) / 6
```

I'll have a look in the evening what is going on here.

**Comment by adtzlr** [comment]
Doing it the finite element way, the volume of the above cell is also positive:

```python
def basis(rst):
    "Basis functions for Tetrahedron."
    r, s, t = rst
    return np.array([[1 - r - s - t],
                     [r],
                     [s],
                     [t]])

def basisprime(rst):
    "Basis functions derivative for Tetrahedron."
    r, s, t = rst
    return np.array([[-1, -1, -1],
                     [ 1,  0,  0],
                     [ 0,  1,  0],
                     [ 0,  0,  1]])

from types import SimpleNamespace

quadrature = SimpleNamespace() # I know there's quadpy...
quadrature.points = np.array([[1 / 3, 1 / 3, 1 / 3]])
quadrature.weights = np.array([1 / 6])

dhdr = np.array([basisprime(point) for point in quadrature.points])

# a ... vertex no. a
# i ... coordinate of vertex
# j ... j-th column of partial derivative of basis function
dXdr = np.einsum("ai,...aj->...ij", points, dhdr)

cell_volume = np.sum(np.linalg.det(dXdr) * quadrature.weights)
```

I hope the code is clear enough - did my best 😊. Actually THAT was the reason I came across this "Issue".

**Comment by nschloe** [comment]
You're right, it's weird. Not sure if there's a canon here. I've asked on [stackexchange](https://math.stackexchange.com/q/4209203/36678).

**Comment by nschloe** [comment]
Perhaps in favor of your approach: For a 1D simplex, `[[0.0], [1.0]]` is positive.
```python
import numpy as np

p = np.array([[0.0], [1.0]])
# p = np.array([[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]])
# p = np.array([[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]])

A = np.column_stack(p)
A = np.pad(A, ((0, 1), (0, 0)), constant_values=1.0)
print(A)
vol = np.linalg.det(A) / 2
print(vol)

print()
A = np.column_stack([p[k] - p[0] for k in range(1, len(p))])
print(A)
vol = np.linalg.det(A) / 2
print(vol)
```

**Comment by adtzlr** [comment]
> Perhaps in favor of your approach: For a 1D simplex, [[0.0], [1.0]] is positive.

Nice example! So the first method (slightly modified; `n` is the n-dimensional space here, not the no. of vertices)

```python
import numpy as np

# n = 1
p = np.array([[0.0], [1.0]])

A = np.column_stack(p)
A = np.pad(A, ((0, 1), (0, 0)), constant_values=1.0)
print(A)
vol = np.linalg.det(A) / 1
print(vol)
```

doesn't make sense for `n=(1,3)` as the calculated volume is negative!? Anyway, thanks for all the hints! If I stumble open a good explanation in the future, I'll let you know... 😃

**Comment by nschloe** [comment]
> doesn't make sense for n=(1,3) as the calculated volume is negative!?

It seems like that. I'll let that sit for a few more days and then perhaps change the ordering.

**Comment by nschloe** [comment]
> It seems like that. I'll let that sit for a few more days and then perhaps change the ordering.

I did change it in meshzoo and meshplex now. The argument that 1D intervals $`[a, b]`$ with $`a < b`$ should be positive is convincing enough. Hopefully this now simplifies some of your tasks.

**Comment by adtzlr** [comment]
> Hopefully this now simplifies some of your tasks.

Definitely, thanks! And hopefully not only for me 😃
