### ISSUE TITLE
cube_quad?

### ISSUE THREAD

**Issue by osullivryan** [nschloe/meshzoo#77]
Hello!

First, awesome project!

I was wondering if you had an idea of how to implement a `cube_quad`. I can think of a handful of ways, but none seem efficient. 

This would really just be the outer shell of a cube, but still very useful!

Thanks again!

**Comment by nschloe** [comment]
I can't think of a better way than "just doing it". It'll be an index battle, but that's what it is.

**Comment by nschloe** [comment]
Closing for lack of response. Feel free to reopen at any time!
