### ISSUE TITLE
Feature request: Non uniform structured meshes

### ISSUE THREAD

**Issue by kayarre** [nschloe/meshzoo#80]
I am doing some work to extend the grid options in a scientific code, but would like to
“Test out” structured nonuniform Cartesian, Cylindrical, and Spherical meshes. I haven’t looked deeply if meshzoo has those features but if that is of interest I would like to work on contributing that.

**Comment by nschloe** [comment]
What meshes do you mean exactly?

**Comment by nschloe** [comment]
> An example of what i am thinking about would be geometric spacing between cells for a Cartesian grid.

Aha, you mean like boundary layers etc.? That should be easy to do for rectangles and cubes, which I suppose you're referring to.

> So adding a mesh generator for a Cartesian grid that adds ‘r’ for the geometric factor for the mesh spacing in each dimension for a structured grid.

Let's go more general and allow the x/y/z values of the grid to be passed.

> Then I am interested in something similar for cylindrical and spherical coordinate based meshes.

I can't imagine what you have in mind here.

**Comment by kayarre** [comment]
Yes thank you. rectangles and cubes exactly. 

I am good with passing the x, y, z values. I think what you mean is generally be able to specify the "widths" or a list of points. I also want to test out using a "generator", i.e. be able use the the more general specification of cell widths in x, y, z, but be able to call something that generates the cell widths or passes in a function that generates it. I am not sure that right language here.

as far as cylindrical or spherical I mean essentially the same for rectangles and cubes but projected into spherical and cylindrical coordinates. I haven't started digging, but think this seemed like a good place to share those efforts if it fits.
