### ISSUE TITLE
Saving with meshio from cube example doesn't work 

### ISSUE THREAD

**Issue by simonecesano** [nschloe/meshzoo#84]
I'm trying to use the cube example and then saving to a file like this:
 
    import meshzoo
    import numpy as np
    
    points, cells = meshzoo.cube_tetra(
        np.linspace(0.0, 1.0, 11), np.linspace(0.0, 1.0, 11), np.linspace(0.0, 1.0, 11)
    )
    
    # this fails
    meshio.write_points_cells("triangle.vtk", points, cells)

fails with 

    ValueError: too many values to unpack (expected 2)

which is too bad because this is a lovely module

**Comment by nschloe** [comment]
You need to tell meshio what cell type it is:
```python
meshio.write_points_cells("triangle.vtk", points, {"tetra": cells})
```
