### ISSUE TITLE
Meshing cuboid with higher aspect ratio not working

### ISSUE THREAD

**Issue by LouisSchreyer** [nschloe/meshzoo#87]
I wanted to create meshed cuboids (with hex and tet meshes) with "high" aspect ratios using `meshzoo.cube_hexa()` and `meshzoo.cube_tetra()`. But the meshes are flawed for those higher aspect ratios. Especially if the dimensions differ in all space directions.

I made a little working example:

```python
import meshzoo  # Version 0.9.0
import meshio
import numpy as np

offset = [0.0, 0.0, 0.0]
size = [2.0, 6.0, 1.0]
mesh_size = 0.5

points, _cells = meshzoo.cube_hexa(
    np.linspace(offset[0], offset[0] + size[0], int(round(size[0] / mesh_size)) + 1),
    np.linspace(offset[1], offset[1] + size[1], int(round(size[1] / mesh_size)) + 1),
    np.linspace(offset[2], offset[2] + size[2], int(round(size[2] / mesh_size)) + 1),
)

cells = [("hexahedron", _cells)]

mesh = meshio.Mesh(points, cells)

meshio.vtk.write("cuboid.vtk", mesh)
```

Is it possible to extend the cube functionality to work with general cuboids?

**Comment by nschloe** [comment]
What do you mean, "flawed"?

**Comment by LouisSchreyer** [comment]
When I execute the example code and open the cuboid.vtk in paraview (5.8.1) it looks like:
![image](https://user-images.githubusercontent.com/72546478/145769879-cf4fb037-4937-4ebb-9289-59813dad77ca.png)


When I use `meshzoo.cube_tetra()` function in the example code instead, the following Error is thrown:
```
Traceback (most recent call last):
  File "minimalbsp_meshzoo.py", line 13, in <module>
    np.linspace(offset[2], offset[2] + size[2], int(round(size[2] / mesh_size)) + 1),
  File "C:\GITRepository\initialcharge\venv\lib\site-packages\meshzoo\_cube.py", line 142, in cube_tetra
    [c[0][idx], c[1][idx], c[3][idx], c[4][idx]],
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 4
```

**Comment by nschloe** [comment]
Got you! Looking at it now.

**Comment by nschloe** [comment]
Fixed now.
