### ISSUE TITLE
License discrepancy?

### ISSUE THREAD

**Issue by kayarre** [nschloe/meshzoo#89]
it looks like MIT is mentioned in [README.md ](https://github.com/nschloe/meshzoo/blob/main/README.md)

but [LICENSE.txt](https://github.com/nschloe/meshzoo/blob/main/LICENSE.txt) is LGPL?

**Comment by nschloe** [comment]
Good call! meshzoo is GPL'd, that's also the license in `setup.cfg`. REAMDE fix incoming.
