### ISSUE TITLE
where can I find version 0.3.1?

### ISSUE THREAD

**Issue by xhuan8** [nschloe/meshzoo#96]
there are some old code uses meshzoo 0.3.1, which should work on Python 3.6.

**Comment by nschloe** [comment]
Python 3.6's end of life has been reached long ago. Using it can pose security hazards and should be avoided.

**Comment by defzhangaa** [comment]
No, it seems too arbitrary. A great deal of hard-to-maintain code was developed in earlier versions of Python. You cannot force us to abandon older Python versions just because of vulnerabilities.
